services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ./config/homeassistant.yaml:/config/configuration.yaml
    restart: unless-stopped
    privileged: true
    network_mode: host

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mosquitto:/mosquitto:rw
      # Make config RO to prevent container from chowning it.
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  zigbee2mqtt:
      container_name: zigbee2mqtt
      image: ghcr.io/koenkk/zigbee2mqtt
      restart: unless-stopped
      volumes:
          - zigbee2mqtt:/app/data
          - /run/udev:/run/udev:ro
      ports:
          # Frontend port
          - 8081:8080
      environment:
          - TZ=Europe/Berlin
      devices:
          # Make sure this matched your adapter location
          - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230804194557-if00:/dev/ttyACM0

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=${DOMAIN}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=hetzner
      - EMAIL=${EMAIL}
      - HETZNER_API_TOKEN
    volumes:
      - swag:/config
      - ./config/site-confs:/config/nginx/site-confs
      - ./config/index.html.template:/config/www/index.html.template
      - ./config/90_swag_envsub.sh:/custom-cont-init.d/90_envsub.sh
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8080:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      # - "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'Europe/Berlin'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - 'pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      # - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      # - SYS_NICE
    restart: unless-stopped

  hetzner-ddns:
    container_name: hetzner-ddns
    build:
      context: hetzner-api-dyndns-docker
      network: host
    environment:
      HETZNER_AUTH_API_TOKEN: ${HETZNER_API_TOKEN}
      HETZNER_ZONE_NAME: ${DOMAIN}
      HETZNER_RECORD_NAME: '@'
      HETZNER_RECORD_TTL: '60'
      HETZNER_RECORD_TYPE: AAAA
    restart: unless-stopped
    network_mode: host

  web-logbook:
    container_name: web-logbook
    image: vsimakhin/web-logbook:latest
    command: -dsn /data/web-logbook.sql
    restart: unless-stopped
    user: root
    ports:
      - 4000:4000
    volumes:
      - web-logbook:/data

  backup:
    container_name: backup
    image: offen/docker-volume-backup:latest
    restart: unless-stopped
    volumes:
      - homeassistant:/backup/homeassistant:ro
      - swag:/backup/swag:ro
      - pihole:/backup/pihole:ro
      - web-logbook:/backup/web-logbook:ro
      - zigbee2mqtt:/backup/zigbee2mqtt:ro
      - mosquitto:/backup/mosquitto:ro
    environment:
      BACKUP_CRON_EXPRESSION: "0 4 * * MON"
      AWS_S3_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ENDPOINT: ${AWS_ENDPOINT}

volumes:
  homeassistant:
  swag:
  pihole:
  dnsmasq:
  web-logbook:
  zigbee2mqtt:
  mosquitto:
